### ISSUE TITLE
It seems it can't build with Clang 10

### ISSUE THREAD

**Issue by Faalagorn** [codenamecpp/carnage3d#20]
It seems that it doesn't build in Clang 10 due to lack of libclang_rt.asan-x86_64.a I'm a bit tired to properly troubleshoot it now, but quick googling returned that this file is no longer used in Clang/Compiler-rt.

**Comment by neuromancer** [comment]
Uhm, feel free to disable the sanitizers if they are causing trouble for you. They were enabled in [this PR](https://github.com/codenamecpp/carnage3d/pull/19/files), so revert that lines and it should be working for you. I tested it with Clang 9, I will check how they should be used in Clang 10 and create another PR to fix it.

**Comment by Faalagorn** [comment]
Thanks for the quick reply and pointing out to the commit! It may be something on my side after all, since by removing the sanitizer checks, I still can't compile it apparently, so maybe it's something unrelated. I'll take more of a look at it tomorrow and close that issue until then, as I probably could use some sleep before troubleshooting :P

**Comment by neuromancer** [comment]
Clang 10 is not in Arch yet, but as soon as it is available I will re-compile and check if I had the same issue, so this should be eventually solved.
